apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: spam-analyzer
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000