apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: spam-analyzer
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      nodePort: 30080
